version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=dev-change-me
    depends_on:
      - sqlite
    volumes:
      - ./config:/app/config
      - ./data:/app/data
  sqlite:
    image: keinos/sqlite3:3.46
    command: ["tail", "-f", "/dev/null"]
  redis:
    image: redis:7
    ports: ["6379:6379"]